name: Nextflow tests
# This workflow runs the PhyloNext pipeline with the minimal test dataset to check that it completes without any syntax errors
on:
  push:
    branches:
      - main
  pull_request:
  release:
    types: [published]

# Cancel if a newer run is started
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true



jobs:
  test:
    name: Run PhyloNext pipeline with test data
    if: ${{ github.event_name != 'push' || (github.event_name == 'push' && github.repository == 'vmikk/PhyloNext') }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Nextflow versions
        include:
          # Test pipeline minimum Nextflow version
          - NXF_VER: '22.10.4'
            NXF_EDGE: ''
          # # Test latest edge release of Nextflow
          # - NXF_VER: ''
          #   NXF_EDGE: '1'
    env:
      NXF_ANSI_LOG: false
      # CAPSULE_LOG: none
    steps:
      - name: Check out pipeline code
        uses: actions/checkout@v3
        with:
          ref: main
          fetch-depth: 1

      # pwd = /__w/PhyloNext/PhyloNext

      - name: Install Nextflow
        env:
          NXF_VER: ${{ matrix.NXF_VER }}
          # Uncomment only if the edge release is more recent than the latest stable release
          # See https://github.com/nextflow-io/nextflow/issues/2467
          # NXF_EDGE: ${{ matrix.NXF_EDGE }}
        run: |
          wget -qO- get.nextflow.io | bash
          sudo mv nextflow /usr/local/bin/

      - name: Run pipeline usning built-in phylogenetic tree
        run: |
          nextflow run ${GITHUB_WORKSPACE} -profile test,docker

      - name: Output log on failure
        if: failure()
        run: |
          sudo apt install bat > /dev/null
          batcat --decorations=always --color=always /home/runner/work/PhyloNext/PhyloNext/.nextflow.log

      - name: Upload logs on failure
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: logs-builtin-tree
          path: |
            /home/runner/work/PhyloNext/PhyloNext/.nextflow.log
            /home/runner/work/PhyloNext/PhyloNext/work/**/.command.log

      - name: Run pipeline and fetch phylogenetic tree from OToL
        run: |
          nextflow run ${GITHUB_WORKSPACE} -profile test_ott,docker --maxage 111

