name: PhyloNext automated tests [Open Tree of Life container]
# This workflow runs tests for the OToL-related part of the PhyloNext pipeline
on: push

jobs:
  biodiverse-tests:
    name: Run Biodiverse tests
    runs-on: ubuntu-latest
    container: 
      image: vmikk/opentree:0.0.2
      volumes:
        - ${{ github.workspace }}:/ott
    steps:

      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Fetching test tree from OToL
        run: |
          python \
            /ott/bin/scripts/induced_synth_subtree_from_csv.py \
            --query /ott/test_data/Felidae,Canidae_Species_OTT.csv \
            --output_dir /ott/OTT/ \
            --phylo-only \
            --max-age 111

      - name: Verifying results
        run: ls -l /ott/OTT/
