name: PhyloNext automated tests [Open Tree of Life container]
# This workflow runs tests for the OToL-related part of the PhyloNext pipeline
on: push

jobs:
  biodiverse-tests:
    name: Run OToL tests
    runs-on: ubuntu-latest
    container: 
      image: vmikk/opentree:0.0.2
      volumes:
        - ${{ github.workspace }}:/ott
    steps:

      - name: Check out the repo
        uses: actions/checkout@v3
        with:
          ref: main
          fetch-depth: 1

      # pwd = /__w/PhyloNext/PhyloNext

      - name: Fetching test tree from OToL
        run: |
          python \
            /__w/PhyloNext/PhyloNext/bin/induced_synth_subtree_from_csv.py \
            --query /__w/PhyloNext/PhyloNext/test_data/Felidae,Canidae_Species_OTT.csv \
            --output_dir $(pwd)/OTT/ \
            --phylo-only \
            --max-age 111

      - name: Verifying results
        run: |
          ls -l $(pwd)/OTT/

      - name: Check file existence
        id: check_files
        uses: andstor/file-existence-action@v2
        with:
          files: "$(pwd)/OTT/ott_label_dated_tree.tre"

      - name: File exists
        if: steps.check_files.outputs.files_exists == 'true'
        run: echo "Looks good, Labeled and dated phylogenetic tree is in place!"
